app:
  paths:
    photos: /home/kalle/test
    backup: /home/kalle/photo_backup
  aws:
    bucket: bucketName
  redis:
    keys:
      upload-key: UPLOAD
      zip-key: ZIP
  schedules:
    zip: '@hourly'
    upload: '@midnight'

spring:
  redis:
    host: localhost
    port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health,env
