app:
  paths:
    photos:
    backup:
    download:
  aws:
    s3:
      bucket-name:
      restore-duration-in-days:
    sqs:
      queue-name:
  redis:
    keys:
      upload: upload
      zip: zip
      download: download
  scheduling:
    cron:
      zip: '@hourly'
      upload: '@daily'
      download: '@hourly'

spring:
  data:
    redis:
      host: localhost
      port: 6379
