version: "3"

services:
  redis:
    image: redis:7.0
    container_name: redis
    ports: 
      - "6379:6379"
    volumes:
      - "./redis.conf:/usr/local/etc/redis/redis.conf"
      - "./data:/data"
    command: "redis-server /usr/local/etc/redis/redis.conf"
    networks:
      - redis

networks:
  redis:
    external: true
